import PageHeader from '../components/ui/PageHeader';
import SectionWrapper from '../components/ui/SectionWrapper';
import { HOSPITAL } from '../lib/constants';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing and using the ${HOSPITAL.name} website, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our website or services.`,
  },
  {
    title: '2. Website Use',
    content: `This website is intended to provide general information about our hospital, services, and health resources. The content is for informational purposes only and does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for medical concerns.`,
  },
  {
    title: '3. Appointment Booking',
    content: `Online appointment bookings are subject to availability and confirmation. We reserve the right to reschedule or cancel appointments due to unforeseen circumstances. Patients are expected to arrive 15 minutes before their scheduled time. Cancellations should be made at least 4 hours in advance.`,
  },
  {
    title: '4. AI Features Disclaimer',
    content: `Our AI Symptom Checker and AI Chat Assistant are informational tools only. They do not provide medical diagnoses and should not replace professional medical advice. Results from these tools are generated by algorithms and may not be accurate for all situations. Always consult a doctor for proper diagnosis.`,
  },
  {
    title: '5. User Accounts & Data',
    content: `You are responsible for maintaining the confidentiality of any account credentials. You agree to provide accurate, current, and complete information. We reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: '6. Intellectual Property',
    content: `All content on this website — including text, graphics, logos, images, and software — is the property of ${HOSPITAL.name} and is protected by copyright and intellectual property laws. You may not reproduce, distribute, or modify any content without written permission.`,
  },
  {
    title: '7. Limitation of Liability',
    content: `${HOSPITAL.name} shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of this website. We make no warranties regarding the accuracy, completeness, or reliability of the information provided.`,
  },
  {
    title: '8. Third-Party Links',
    content: `Our website may contain links to third-party websites. We are not responsible for the content, privacy practices, or availability of these external sites. Accessing them is at your own risk.`,
  },
  {
    title: '9. Governing Law',
    content: `These terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in New Delhi.`,
  },
  {
    title: '10. Changes to Terms',
    content: `We reserve the right to modify these Terms of Service at any time. Changes will be effective upon posting to this page. Your continued use of the website after changes constitutes acceptance of the updated terms.`,
  },
];

export default function Terms() {
  return (
    <>
      <PageHeader
        title="Terms of Service"
        subtitle={`Last updated: January 1, 2026 — ${HOSPITAL.name}`}
        breadcrumbs={[{ label: 'Terms of Service' }]}
      />

      <SectionWrapper background="white">
        <div className="max-w-3xl mx-auto">
          <p className="text-dark-600 leading-relaxed mb-8">
            Please read these Terms of Service carefully before using the {HOSPITAL.name} website. These terms govern your use of our website and the services we provide online.
          </p>

          <div className="space-y-8">
            {sections.map((s) => (
              <div key={s.title}>
                <h3 className="text-lg font-bold text-dark-900 mb-2">{s.title}</h3>
                <p className="text-dark-600 leading-relaxed">{s.content}</p>
              </div>
            ))}
          </div>

          <div className="mt-10 p-5 rounded-xl bg-primary-50 ring-1 ring-primary-200">
            <p className="text-sm text-dark-700">
              <strong>Questions about these terms?</strong> Contact us at{' '}
              <a href={`mailto:${HOSPITAL.email}`} className="text-primary-600 font-semibold hover:underline">
                {HOSPITAL.email}
              </a>{' '}
              or call{' '}
              <a href={`tel:${HOSPITAL.phone}`} className="text-primary-600 font-semibold hover:underline">
                {HOSPITAL.phone}
              </a>.
            </p>
          </div>
        </div>
      </SectionWrapper>
    </>
  );
}
